/**
 * Generates every Android launcher and splash resource from the one mark.
 *
 *   pnpm --filter @gradtools/web android:icons
 *
 * Source of truth: src/brand/gradtools-mark.svg (a single `currentColor` path
 * on a 64-unit grid). Nothing here is drawn by hand:
 *
 *   drawable/ic_launcher_foreground.xml  the mark as a VECTOR, white, scaled
 *                                        into the adaptive icon's 66dp safe
 *                                        zone. Also the Android 13 monochrome
 *                                        (themed) icon, which only reads alpha.
 *   values/ic_launcher_background.xml    the brand ground (blood red).
 *   mipmap-anydpi-v26/ic_launcher*.xml   adaptive icon: background, foreground,
 *                                        monochrome. API 26+ uses only these.
 *   mipmap-<density>/ic_launcher*.png    legacy icons for API 24–25, rendered
 *                                        from the same SVG by Chromium at each
 *                                        density's exact pixel size.
 *   drawable/splash.xml                  the pre-Android-12 launch background:
 *                                        brand ground with the mark centred.
 *
 * Re-run after changing the mark; commit the output.
 */

import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { chromium } from '@playwright/test';

const WEB = join(dirname(fileURLToPath(import.meta.url)), '..');
const RES = join(WEB, 'android/app/src/main/res');
const BRAND = '#8B0015';
const MARK = '#FFFFFF';

const svg = await readFile(join(WEB, 'src/brand/gradtools-mark.svg'), 'utf8');
const d = /\sd="([^"]+)"/.exec(svg)?.[1];
if (d === undefined) throw new Error('gradtools-mark.svg has no path');

/*
 * Adaptive icon geometry. The canvas is 108dp; launchers mask it to shapes
 * that are guaranteed to show only the central 66dp circle. The mark's
 * farthest point (a cap tip) is 32.2 units from its optical centre (32, 33),
 * so a 0.9 scale keeps all of it within 29dp of the centre — inside the safe
 * zone with room to spare, and large enough not to look lost.
 */
const SCALE = 0.9;
const [CX, CY] = [32, 33];
const tx = 54 - CX * SCALE;
const ty = 54 - CY * SCALE;

const write = async (path, text) => {
  await mkdir(dirname(join(RES, path)), { recursive: true });
  await writeFile(join(RES, path), text);
};

await write(
  'drawable/ic_launcher_foreground.xml',
  `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/android-icons.mjs from src/brand/gradtools-mark.svg. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
    <group
        android:scaleX="${SCALE}"
        android:scaleY="${SCALE}"
        android:translateX="${tx.toFixed(2)}"
        android:translateY="${ty.toFixed(2)}">
        <path
            android:fillColor="${MARK}"
            android:pathData="${d}" />
    </group>
</vector>
`,
);

await write(
  'values/ic_launcher_background.xml',
  `<?xml version="1.0" encoding="utf-8"?>
<resources>
    <color name="ic_launcher_background">${BRAND}</color>
</resources>
`,
);

const adaptive = `<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/ic_launcher_background" />
    <foreground android:drawable="@drawable/ic_launcher_foreground" />
    <monochrome android:drawable="@drawable/ic_launcher_foreground" />
</adaptive-icon>
`;
await write('mipmap-anydpi-v26/ic_launcher.xml', adaptive);
await write('mipmap-anydpi-v26/ic_launcher_round.xml', adaptive);

await write(
  'drawable/splash.xml',
  `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/android-icons.mjs. -->
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:drawable="@color/ic_launcher_background" />
    <item
        android:width="108dp"
        android:height="108dp"
        android:drawable="@drawable/ic_launcher_foreground"
        android:gravity="center" />
</layer-list>
`,
);

/* Legacy PNGs: 48dp at each density. Rendered, not resampled. */
const DENSITIES = { mdpi: 48, hdpi: 72, xhdpi: 96, xxhdpi: 144, xxxhdpi: 192 };
const browser = await chromium.launch();
try {
  const page = await browser.newPage();
  for (const [density, px] of Object.entries(DENSITIES)) {
    for (const [name, radius] of [
      ['ic_launcher', '22%'],
      ['ic_launcher_round', '50%'],
    ]) {
      await page.setViewportSize({ width: px, height: px });
      await page.setContent(`<!doctype html><html><body style="margin:0;background:transparent">
        <div style="width:${px}px;height:${px}px;border-radius:${radius};background:${BRAND};display:grid;place-items:center">
          <svg viewBox="0 0 64 64" width="${px * 0.66}" height="${px * 0.66}"><path fill="${MARK}" d="${d}"/></svg>
        </div></body></html>`);
      await mkdir(join(RES, `mipmap-${density}`), { recursive: true });
      await page.screenshot({
        path: join(RES, `mipmap-${density}`, `${name}.png`),
        omitBackground: true,
      });
    }
  }
} finally {
  await browser.close();
}

/* Capacitor's template assets, now unused. */
const stale = [
  'drawable-v24/ic_launcher_foreground.xml',
  'drawable/ic_launcher_background.xml',
  'drawable/splash.png',
  ...Object.keys(DENSITIES).map((density) => `mipmap-${density}/ic_launcher_foreground.png`),
  ...['land', 'port'].flatMap((o) =>
    ['mdpi', 'hdpi', 'xhdpi', 'xxhdpi', 'xxxhdpi'].map(
      (density) => `drawable-${o}-${density}/splash.png`,
    ),
  ),
];
for (const path of stale) await rm(join(RES, path), { force: true });

console.log('Android icons and splash generated from gradtools-mark.svg');
